In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import seaborn as sns

In [2]:
df=pd.read_csv("C:\\Users\\vivsw\\Downloads\\credit_customers.csv")
print(len(df))
df.head()

1000


checking_status  duration                  credit_history  \
0              <0         6  critical/other existing credit   
1        0<=X<200        48                   existing paid   
2     no checking        12  critical/other existing credit   
3              <0        42                   existing paid   
4              <0        24              delayed previously   

               purpose  credit_amount    savings_status employment  \
0             radio/tv           1169  no known savings        >=7   
1             radio/tv           5951              <100     1<=X<4   
2            education           2096              <100     4<=X<7   
3  furniture/equipment           7882              <100     4<=X<7   
4              new car           4870              <100     1<=X<4   

   installment_commitment     personal_status other_parties  ...  \
0                       4         male single          none  ...   
1                       2  female div/dep/mar          none  ...   
2                       2         male single          none  ...   
3                       2         male single     guarantor  ...   
4                       3         male single          none  ...   

   property_magnitude age  other_payment_plans   housing existing_credits  \
0         real estate  67                 none       own                2   
1         real estate  22                 none       own                1   
2         real estate  49                 none       own                1   
3      life insurance  45                 none  for free                1   
4   no known property  53                 none  for free                2   

                  job num_dependents  own_telephone foreign_worker class  
0             skilled              1            yes            yes  good  
1             skilled              1           none            yes   bad  
2  unskilled resident              2           none            yes  good  
3             skilled              2           none            yes  good  
4             skilled              2           none            yes   bad  

[5 rows x 21 columns]

In [3]:
df.isnull().sum()  

checking_status           0
duration                  0
credit_history            0
purpose                   0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df.dtypes

checking_status           object
duration                   int64
credit_history            object
purpose                   object
credit_amount              int64
savings_status            object
employment                object
installment_commitment     int64
personal_status           object
other_parties             object
residence_since            int64
property_magnitude        object
age                        int64
other_payment_plans       object
housing                   object
existing_credits           int64
job                       object
num_dependents             int64
own_telephone             object
foreign_worker            object
class                     object
dtype: object

In [6]:
foreign_worker=pd.get_dummies(df['foreign_worker'],drop_first=True)
foreign_worker.head()

yes
0    1
1    1
2    1
3    1
4    1

In [7]:
job=pd.get_dummies(df['job'],drop_first=True)
job.head()

skilled  unemp/unskilled non res  unskilled resident
0        1                        0                   0
1        1                        0                   0
2        0                        0                   1
3        1                        0                   0
4        1                        0                   0

In [8]:
housing=pd.get_dummies(df['housing'],drop_first=True)
housing.head()

own  rent
0    1     0
1    1     0
2    1     0
3    0     0
4    0     0

In [9]:
other_payment_plans=pd.get_dummies(df['other_payment_plans'],drop_first=True)
other_payment_plans.head()

none  stores
0     1       0
1     1       0
2     1       0
3     1       0
4     1       0

In [10]:
property_magnitude=pd.get_dummies(df['property_magnitude'],drop_first=True)
property_magnitude.head()

life insurance  no known property  real estate
0               0                  0            1
1               0                  0            1
2               0                  0            1
3               1                  0            0
4               0                  1            0

In [11]:
other_parties=pd.get_dummies(df['other_parties'],drop_first=True)
other_parties.head()

guarantor  none
0          0     1
1          0     1
2          0     1
3          1     0
4          0     1

In [12]:
personal_status=pd.get_dummies(df['personal_status'],drop_first=True)
personal_status.head()

male div/sep  male mar/wid  male single
0             0             0            1
1             0             0            0
2             0             0            1
3             0             0            1
4             0             0            1

In [13]:
employment=pd.get_dummies(df['employment'],drop_first=True)
employment.head()

4<=X<7  <1  >=7  unemployed
0       0   0    1           0
1       0   0    0           0
2       1   0    0           0
3       1   0    0           0
4       0   0    0           0

In [14]:
checking_status=pd.get_dummies(df['checking_status'],drop_first=True)
checking_status.head()

<0  >=200  no checking
0   1      0            0
1   0      0            0
2   0      0            1
3   1      0            0
4   1      0            0

In [15]:
own_telephone=pd.get_dummies(df['own_telephone'],drop_first=True)
own_telephone.head()

yes
0    1
1    0
2    0
3    0
4    0

In [16]:
credit_history=pd.get_dummies(df['credit_history'],drop_first=True)
credit_history.head()

critical/other existing credit  delayed previously  existing paid  \
0                               1                   0              0   
1                               0                   0              1   
2                               1                   0              0   
3                               0                   0              1   
4                               0                   1              0   

   no credits/all paid  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0

In [17]:
savings_status=pd.get_dummies(df['savings_status'],drop_first=True)
savings_status.head()

500<=X<1000  <100  >=1000  no known savings
0            0     0       0                 1
1            0     1       0                 0
2            0     1       0                 0
3            0     1       0                 0
4            0     1       0                 0

In [18]:
purpose=pd.get_dummies(df['purpose'],drop_first=True)
purpose.head()

domestic appliance  education  furniture/equipment  new car  other  \
0                   0          0                    0        0      0   
1                   0          0                    0        0      0   
2                   0          1                    0        0      0   
3                   0          0                    1        0      0   
4                   0          0                    0        1      0   

   radio/tv  repairs  retraining  used car  
0         1        0           0         0  
1         1        0           0         0  
2         0        0           0         0  
3         0        0           0         0  
4         0        0           0         0

In [19]:
df=df.rename(columns={'class': 'outcome'})

In [20]:
outcome=pd.get_dummies(df['outcome'],drop_first=True)
outcome.head()

good
0     1
1     0
2     1
3     1
4     0

In [21]:
df=pd.concat([df,checking_status,credit_history,purpose,savings_status,employment,personal_status,other_parties,property_magnitude,other_payment_plans,housing,job,own_telephone,foreign_worker,outcome],axis=1)
df.head()

checking_status  duration                  credit_history  \
0              <0         6  critical/other existing credit   
1        0<=X<200        48                   existing paid   
2     no checking        12  critical/other existing credit   
3              <0        42                   existing paid   
4              <0        24              delayed previously   

               purpose  credit_amount    savings_status employment  \
0             radio/tv           1169  no known savings        >=7   
1             radio/tv           5951              <100     1<=X<4   
2            education           2096              <100     4<=X<7   
3  furniture/equipment           7882              <100     4<=X<7   
4              new car           4870              <100     1<=X<4   

   installment_commitment     personal_status other_parties  ...  none stores  \
0                       4         male single          none  ...     1      0   
1                       2  female div/dep/mar          none  ...     1      0   
2                       2         male single          none  ...     1      0   
3                       2         male single     guarantor  ...     1      0   
4                       3         male single          none  ...     1      0   

   own rent skilled  unemp/unskilled non res unskilled resident yes yes good  
0    1    0       1                        0                  0   1   1    1  
1    1    0       1                        0                  0   0   1    0  
2    1    0       0                        0                  1   0   1    1  
3    0    0       1                        0                  0   0   1    1  
4    0    0       1                        0                  0   0   1    0  

[5 rows x 63 columns]

In [22]:
df.drop(['checking_status','credit_history','purpose','savings_status','employment','personal_status','other_parties','property_magnitude','other_payment_plans','housing','job','own_telephone','foreign_worker','outcome'],axis=1,inplace=True)

In [23]:
df.head()

duration  credit_amount  installment_commitment  residence_since  age  \
0         6           1169                       4                4   67   
1        48           5951                       2                2   22   
2        12           2096                       2                3   49   
3        42           7882                       2                4   45   
4        24           4870                       3                4   53   

   existing_credits  num_dependents  <0  >=200  no checking  ...  none  \
0                 2               1   1      0            0  ...     1   
1                 1               1   0      0            0  ...     1   
2                 1               2   0      0            1  ...     1   
3                 1               2   1      0            0  ...     1   
4                 2               2   1      0            0  ...     1   

   stores  own  rent  skilled  unemp/unskilled non res  unskilled resident  \
0       0    1     0        1                        0                   0   
1       0    1     0        1                        0                   0   
2       0    1     0        0                        0                   1   
3       0    0     0        1                        0                   0   
4       0    0     0        1                        0                   0   

   yes  yes  good  
0    1    1     1  
1    0    1     0  
2    0    1     1  
3    0    1     1  
4    0    1     0  

[5 rows x 49 columns]

In [24]:
from sklearn.metrics import confusion_matrix,classification_report

In [25]:
def eval_model(ytest,ypred):
    cm=confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))
    
def mscore(model):
    print('Train Score', model.score(x_train,y_train))
    print('Test Score', model.score(x_test,y_test))

In [26]:
y=df['good']
x=df.drop('good',axis=1)

In [27]:
print(x.shape)
print(y.shape)

(1000, 48)
(1000,)


In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(750, 48)
(750,)
(250, 48)
(250,)


# Logistic Regression

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
m1=LogisticRegression(max_iter=1000)
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [31]:
mscore(m1)

Train Score 0.78
Test Score 0.752


In [32]:
ypred_m1=m1.predict(x_test)
eval_model(y_test,ypred_m1)

[[ 35  37]
 [ 25 153]]
              precision    recall  f1-score   support

           0       0.58      0.49      0.53        72
           1       0.81      0.86      0.83       178

    accuracy                           0.75       250
   macro avg       0.69      0.67      0.68       250
weighted avg       0.74      0.75      0.74       250



In [55]:
print('Accuracy of Logistic Regression model is', (35+153)/(35+153+25+37))

Accuracy of Logistic Regression model is 0.752


# KNN Classification

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
m2=KNeighborsClassifier(n_neighbors=15)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [35]:
mscore(m2)

Train Score 0.72
Test Score 0.688


In [36]:
ypred_m2=m2.predict(x_test)
eval_model(y_test,ypred_m2)

[[ 10  62]
 [ 16 162]]
              precision    recall  f1-score   support

           0       0.38      0.14      0.20        72
           1       0.72      0.91      0.81       178

    accuracy                           0.69       250
   macro avg       0.55      0.52      0.51       250
weighted avg       0.63      0.69      0.63       250



In [53]:
print('Accuracy of KNN model is', (10+162)/(16+62+10+162))

Accuracy of KNN model is 0.688


# SVM(linear kernel)

In [37]:
from sklearn.svm import SVC

In [41]:
m3=SVC(kernel='linear',C=10)
m3.fit(x_train,y_train)

SVC(C=10, kernel='linear')

In [42]:
mscore(m3)

Train Score 0.7626666666666667
Test Score 0.748


In [43]:
ypred_m3=m3.predict(x_test)
eval_model(y_test,ypred_m3)

[[ 31  41]
 [ 22 156]]
              precision    recall  f1-score   support

           0       0.58      0.43      0.50        72
           1       0.79      0.88      0.83       178

    accuracy                           0.75       250
   macro avg       0.69      0.65      0.66       250
weighted avg       0.73      0.75      0.74       250



In [52]:
print('Accuracy of SVM model (linear kernel) is', (31+156)/(41+22+31+156))

Accuracy of SVM model (linear kernel) is 0.748


In [45]:
m4=SVC(kernel='rbf',C=10)
m4.fit(x_train,y_train)

SVC(C=10)

In [46]:
mscore(m4)

Train Score 0.704
Test Score 0.728


In [47]:
ypred_m4=m4.predict(x_test)
eval_model(y_test,ypred_m4)

[[  4  68]
 [  0 178]]
              precision    recall  f1-score   support

           0       1.00      0.06      0.11        72
           1       0.72      1.00      0.84       178

    accuracy                           0.73       250
   macro avg       0.86      0.53      0.47       250
weighted avg       0.80      0.73      0.63       250



In [51]:
print('Accuracy of SVM model (rbf kernel) is', (4+178)/(0+68+4+178))

Accuracy of SVM model (rbf kernel) is 0.728


Most accurate model for given data is Logistic Regression(m1)